CREATE DATABASE ex_04;
USE ex_04;

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
fullName VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
phone VARCHAR(11) NOT NULL UNIQUE,
permission BIT(1) DEFAULT 1,
status BIT(1) DEFAULT 1
);

CREATE TABLE history(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
point INT NOT NULL,
examDate DATETIME,
FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE exams(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
duration INT CHECK(duration > 0 ),
status BIT(1) DEFAULT 1
);

CREATE TABLE questions(
id INT AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(255) NOT NULL,
exam_id INT NOT NULL,
FOREIGN KEY(exam_id) REFERENCES exams(id),
status BIT(1) DEFAULT 1
);

CREATE TABLE answer(
id INT AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(255) NOT NULL,
question_id INT NOT NULL,
answerTrue BIT(1),
FOREIGN KEY(question_id) REFERENCES questions(id)
);

CREATE TABLE history_detail(
id INT AUTO_INCREMENT PRIMARY KEY,
history_id INT NOT NULL,
question_id INT NOT NULL,
resuslt BIT(1) DEFAULT 1,
FOREIGN KEY(history_id) REFERENCES history(id),
FOREIGN KEY(question_id) REFERENCES questions(id)
);