CREATE DATABASE ex_05;
USE ex_05;

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
fullName VARCHAR(100) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
phone VARCHAR(11) NOT NULL,
permission BIT,
status BIT(1) DEFAULT 1
);

CREATE TABLE address(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
receiveAddress VARCHAR(100) NOT NULL,
receiveName VARCHAR(100) NOT NULL,
receivePhone VARCHAR(11) NOT NULL,
isDefault BIT(1) DEFAULT 1,
FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE catalog(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) UNIQUE NOT NULL,
status BIT(1) DEFAULT 1
);

CREATE TABLE book(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) UNIQUE NOT NULL,
price DOUBLE CHECK(price > 0 ),
stock INT CHECK(stock >= 0 ),
status BIT(1) DEFAULT 1
);

CREATE TABLE book_catalog(
catalog_id INT NOT NULL,
book_id INT NOT NULL,
FOREIGN KEY(catalog_id) REFERENCES catalog(id),
FOREIGN KEY(book_id) REFERENCES book(id)
);

CREATE TABLE orders(
id INT AUTO_INCREMENT PRIMARY KEY,
orderAt DATETIME NOT NULL,
totals DOUBLE CHECK(totals > 0),
user_id INT NOT NULL,
status BIT(1) DEFAULT 1,
FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE order_detail(
id INT AUTO_INCREMENT PRIMARY KEY,
order_id INT NOT NULL,
book_id INT NOT NULL,
quantity INT CHECK(quantity > 0),
unit_price DOUBLE CHECK(unit_price > 0),
FOREIGN KEY(order_id) REFERENCES orders(id),
FOREIGN KEY(book_id) REFERENCES book(id)
);